	let suggestions = 
	["3D printing", 
	"Advanced materials", 
	"Advanced metering", 
	"Air vehicles", 
	"Air-to-water", 
	"Algae", 
	"Packaging", 
	"Alternative proteins",
	"Animal farming", 
	"Animal welfare", 
	"Apiculture", 
	"Apps", 
	"Aquaculture", 
	"Artificial intelligence (AI)", 
	"Automotive",
	"Autonomous vehicles", 
	"Aviation", 
	"Banking"];